# This is a basic workflow to help you get started with Actions

name: build-resume

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - 'markdown/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-resume:
    permissions:
      id-token: write # Allow job to get access to GitHub token
      contents: read  # Allow job to access repo contents

    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/4483140498/locations/global/workloadIdentityPools/github-identity-pool/providers/github'
          service_account: 'github-resume@infra-390806.iam.gserviceaccount.com'

      - name: Build resume
        uses: ./actions

      - name: Upload file
        id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'output/resume.pdf'
          destination: 'resume-thibault-ayanides'